# Generated by Django 5.0.6 on 2024-05-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=100)),
                ('brief_description', models.TextField()),
                ('full_description', models.TextField()),
                ('topic_number', models.IntegerField(unique=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=250)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='thesis_submissions/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectitem')),
            ],
        ),
    ]
