# Generated by Django 5.0.6 on 2024-05-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectitem_supervisor'),
        ('studentGroup', '0004_applyproject_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesissubmit',
            name='authors',
        ),
        migrations.AddField(
            model_name='thesissubmit',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='studentGroup.studentgroup'),
            preserve_default=False,
        ),
    ]
