# Generated by Django 5.0.6 on 2024-05-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_thesissubmit_authors_thesissubmit_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesissubmit',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesissubmit',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
