# Generated by Django 5.0.6 on 2024-05-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_thesissubmit_is_approved_thesissubmit_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesissubmit',
            name='is_rejected',
        ),
        migrations.AlterField(
            model_name='thesissubmit',
            name='is_approved',
            field=models.BooleanField(default=None),
        ),
    ]
