# Generated by Django 5.0.6 on 2024-05-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_thesissubmit_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesissubmit',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
