# Generated by Django 5.0.6 on 2024-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentGroup', '0003_applyproject_cv_zip_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyproject',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
